//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVDWebAPI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVD
    {
        public int dvdID { get; set; }
        public string title { get; set; }
        public int releaseYear { get; set; }
        public int directorID { get; set; }
        public int ratingID { get; set; }
        public string notes { get; set; }
    
        public virtual Director Director { get; set; }
        public virtual Rating Rating { get; set; }
    }
}
